/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAlarmsRouteImport } from './routes/_authenticated/alarms'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedBoardRouteImport } from './routes/_authenticated/board'
import { Route as AuthenticatedCatalogRouteImport } from './routes/_authenticated/catalog'
import { Route as AuthenticatedDevicesRouteImport } from './routes/_authenticated/devices'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedLicenseRouteImport } from './routes/_authenticated/license'
import { Route as AuthenticatedLiveRouteImport } from './routes/_authenticated/live'
import { Route as AuthenticatedMqttRouteImport } from './routes/_authenticated/mqtt'
import { Route as AuthenticatedPointsRouteImport } from './routes/_authenticated/points'
import { Route as AuthenticatedPublishRouteImport } from './routes/_authenticated/publish'
import { Route as AuthenticatedRuntimeRouteImport } from './routes/_authenticated/runtime'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as AuthenticatedUpgradeRouteImport } from './routes/_authenticated/upgrade'
import { Route as AuthenticatedUtilizationRouteImport } from './routes/_authenticated/utilization'
import { Route as AuthenticatedAccountPasswordRouteImport } from './routes/_authenticated/account/password'
import { Route as AuthenticatedIntegrateOpcuaRouteImport } from './routes/_authenticated/integrate/opcua'
import { Route as AuthenticatedIntegrateQueryRouteImport } from './routes/_authenticated/integrate/query'
import { Route as AuthenticatedMonitorDeviceIdRouteImport } from './routes/_authenticated/monitor.$deviceId'
import { Route as AuthenticatedNotifyIndexRouteImport } from './routes/_authenticated/notify/index'
import { Route as AuthenticatedNotifyHistoryRouteImport } from './routes/_authenticated/notify/history'
import { Route as AuthenticatedSinksHttpRouteImport } from './routes/_authenticated/sinks/http'
import { Route as AuthenticatedSinksMqttRouteImport } from './routes/_authenticated/sinks/mqtt'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlarmsRoute = AuthenticatedAlarmsRouteImport.update({
  id: '/alarms',
  path: '/alarms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBoardRoute = AuthenticatedBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatalogRoute = AuthenticatedCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevicesRoute = AuthenticatedDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLicenseRoute = AuthenticatedLicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiveRoute = AuthenticatedLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMqttRoute = AuthenticatedMqttRouteImport.update({
  id: '/mqtt',
  path: '/mqtt',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPointsRoute = AuthenticatedPointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPublishRoute = AuthenticatedPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRuntimeRoute = AuthenticatedRuntimeRouteImport.update({
  id: '/runtime',
  path: '/runtime',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUpgradeRoute = AuthenticatedUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUtilizationRoute =
  AuthenticatedUtilizationRouteImport.update({
    id: '/utilization',
    path: '/utilization',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountPasswordRoute =
  AuthenticatedAccountPasswordRouteImport.update({
    id: '/account/password',
    path: '/account/password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntegrateOpcuaRoute =
  AuthenticatedIntegrateOpcuaRouteImport.update({
    id: '/integrate/opcua',
    path: '/integrate/opcua',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntegrateQueryRoute =
  AuthenticatedIntegrateQueryRouteImport.update({
    id: '/integrate/query',
    path: '/integrate/query',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonitorDeviceIdRoute =
  AuthenticatedMonitorDeviceIdRouteImport.update({
    id: '/monitor/$deviceId',
    path: '/monitor/$deviceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotifyIndexRoute =
  AuthenticatedNotifyIndexRouteImport.update({
    id: '/notify/',
    path: '/notify/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotifyHistoryRoute =
  AuthenticatedNotifyHistoryRouteImport.update({
    id: '/notify/history',
    path: '/notify/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSinksHttpRoute = AuthenticatedSinksHttpRouteImport.update({
  id: '/sinks/http',
  path: '/sinks/http',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSinksMqttRoute = AuthenticatedSinksMqttRouteImport.update({
  id: '/sinks/mqtt',
  path: '/sinks/mqtt',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/sign-in': typeof authSignInRoute
  '/alarms': typeof AuthenticatedAlarmsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/board': typeof AuthenticatedBoardRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/license': typeof AuthenticatedLicenseRoute
  '/live': typeof AuthenticatedLiveRoute
  '/mqtt': typeof AuthenticatedMqttRoute
  '/points': typeof AuthenticatedPointsRoute
  '/publish': typeof AuthenticatedPublishRoute
  '/runtime': typeof AuthenticatedRuntimeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/utilization': typeof AuthenticatedUtilizationRoute
  '/account/password': typeof AuthenticatedAccountPasswordRoute
  '/integrate/opcua': typeof AuthenticatedIntegrateOpcuaRoute
  '/integrate/query': typeof AuthenticatedIntegrateQueryRoute
  '/monitor/$deviceId': typeof AuthenticatedMonitorDeviceIdRoute
  '/notify/history': typeof AuthenticatedNotifyHistoryRoute
  '/sinks/http': typeof AuthenticatedSinksHttpRoute
  '/sinks/mqtt': typeof AuthenticatedSinksMqttRoute
  '/notify/': typeof AuthenticatedNotifyIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/alarms': typeof AuthenticatedAlarmsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/board': typeof AuthenticatedBoardRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/license': typeof AuthenticatedLicenseRoute
  '/live': typeof AuthenticatedLiveRoute
  '/mqtt': typeof AuthenticatedMqttRoute
  '/points': typeof AuthenticatedPointsRoute
  '/publish': typeof AuthenticatedPublishRoute
  '/runtime': typeof AuthenticatedRuntimeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/utilization': typeof AuthenticatedUtilizationRoute
  '/': typeof AuthenticatedIndexRoute
  '/account/password': typeof AuthenticatedAccountPasswordRoute
  '/integrate/opcua': typeof AuthenticatedIntegrateOpcuaRoute
  '/integrate/query': typeof AuthenticatedIntegrateQueryRoute
  '/monitor/$deviceId': typeof AuthenticatedMonitorDeviceIdRoute
  '/notify/history': typeof AuthenticatedNotifyHistoryRoute
  '/sinks/http': typeof AuthenticatedSinksHttpRoute
  '/sinks/mqtt': typeof AuthenticatedSinksMqttRoute
  '/notify': typeof AuthenticatedNotifyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/_authenticated/alarms': typeof AuthenticatedAlarmsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/board': typeof AuthenticatedBoardRoute
  '/_authenticated/catalog': typeof AuthenticatedCatalogRoute
  '/_authenticated/devices': typeof AuthenticatedDevicesRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/license': typeof AuthenticatedLicenseRoute
  '/_authenticated/live': typeof AuthenticatedLiveRoute
  '/_authenticated/mqtt': typeof AuthenticatedMqttRoute
  '/_authenticated/points': typeof AuthenticatedPointsRoute
  '/_authenticated/publish': typeof AuthenticatedPublishRoute
  '/_authenticated/runtime': typeof AuthenticatedRuntimeRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/_authenticated/upgrade': typeof AuthenticatedUpgradeRoute
  '/_authenticated/utilization': typeof AuthenticatedUtilizationRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/account/password': typeof AuthenticatedAccountPasswordRoute
  '/_authenticated/integrate/opcua': typeof AuthenticatedIntegrateOpcuaRoute
  '/_authenticated/integrate/query': typeof AuthenticatedIntegrateQueryRoute
  '/_authenticated/monitor/$deviceId': typeof AuthenticatedMonitorDeviceIdRoute
  '/_authenticated/notify/history': typeof AuthenticatedNotifyHistoryRoute
  '/_authenticated/sinks/http': typeof AuthenticatedSinksHttpRoute
  '/_authenticated/sinks/mqtt': typeof AuthenticatedSinksMqttRoute
  '/_authenticated/notify/': typeof AuthenticatedNotifyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/alarms'
    | '/audit'
    | '/board'
    | '/catalog'
    | '/devices'
    | '/history'
    | '/license'
    | '/live'
    | '/mqtt'
    | '/points'
    | '/publish'
    | '/runtime'
    | '/settings'
    | '/setup'
    | '/upgrade'
    | '/utilization'
    | '/account/password'
    | '/integrate/opcua'
    | '/integrate/query'
    | '/monitor/$deviceId'
    | '/notify/history'
    | '/sinks/http'
    | '/sinks/mqtt'
    | '/notify/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/alarms'
    | '/audit'
    | '/board'
    | '/catalog'
    | '/devices'
    | '/history'
    | '/license'
    | '/live'
    | '/mqtt'
    | '/points'
    | '/publish'
    | '/runtime'
    | '/settings'
    | '/setup'
    | '/upgrade'
    | '/utilization'
    | '/'
    | '/account/password'
    | '/integrate/opcua'
    | '/integrate/query'
    | '/monitor/$deviceId'
    | '/notify/history'
    | '/sinks/http'
    | '/sinks/mqtt'
    | '/notify'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/sign-in'
    | '/_authenticated/alarms'
    | '/_authenticated/audit'
    | '/_authenticated/board'
    | '/_authenticated/catalog'
    | '/_authenticated/devices'
    | '/_authenticated/history'
    | '/_authenticated/license'
    | '/_authenticated/live'
    | '/_authenticated/mqtt'
    | '/_authenticated/points'
    | '/_authenticated/publish'
    | '/_authenticated/runtime'
    | '/_authenticated/settings'
    | '/_authenticated/setup'
    | '/_authenticated/upgrade'
    | '/_authenticated/utilization'
    | '/_authenticated/'
    | '/_authenticated/account/password'
    | '/_authenticated/integrate/opcua'
    | '/_authenticated/integrate/query'
    | '/_authenticated/monitor/$deviceId'
    | '/_authenticated/notify/history'
    | '/_authenticated/sinks/http'
    | '/_authenticated/sinks/mqtt'
    | '/_authenticated/notify/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alarms': {
      id: '/_authenticated/alarms'
      path: '/alarms'
      fullPath: '/alarms'
      preLoaderRoute: typeof AuthenticatedAlarmsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/board': {
      id: '/_authenticated/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof AuthenticatedBoardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog': {
      id: '/_authenticated/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AuthenticatedCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devices': {
      id: '/_authenticated/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AuthenticatedDevicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/license': {
      id: '/_authenticated/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof AuthenticatedLicenseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live': {
      id: '/_authenticated/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AuthenticatedLiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mqtt': {
      id: '/_authenticated/mqtt'
      path: '/mqtt'
      fullPath: '/mqtt'
      preLoaderRoute: typeof AuthenticatedMqttRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/points': {
      id: '/_authenticated/points'
      path: '/points'
      fullPath: '/points'
      preLoaderRoute: typeof AuthenticatedPointsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/publish': {
      id: '/_authenticated/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof AuthenticatedPublishRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/runtime': {
      id: '/_authenticated/runtime'
      path: '/runtime'
      fullPath: '/runtime'
      preLoaderRoute: typeof AuthenticatedRuntimeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/upgrade': {
      id: '/_authenticated/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof AuthenticatedUpgradeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/utilization': {
      id: '/_authenticated/utilization'
      path: '/utilization'
      fullPath: '/utilization'
      preLoaderRoute: typeof AuthenticatedUtilizationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/password': {
      id: '/_authenticated/account/password'
      path: '/account/password'
      fullPath: '/account/password'
      preLoaderRoute: typeof AuthenticatedAccountPasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrate/opcua': {
      id: '/_authenticated/integrate/opcua'
      path: '/integrate/opcua'
      fullPath: '/integrate/opcua'
      preLoaderRoute: typeof AuthenticatedIntegrateOpcuaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrate/query': {
      id: '/_authenticated/integrate/query'
      path: '/integrate/query'
      fullPath: '/integrate/query'
      preLoaderRoute: typeof AuthenticatedIntegrateQueryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitor/$deviceId': {
      id: '/_authenticated/monitor/$deviceId'
      path: '/monitor/$deviceId'
      fullPath: '/monitor/$deviceId'
      preLoaderRoute: typeof AuthenticatedMonitorDeviceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notify/': {
      id: '/_authenticated/notify/'
      path: '/notify'
      fullPath: '/notify/'
      preLoaderRoute: typeof AuthenticatedNotifyIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notify/history': {
      id: '/_authenticated/notify/history'
      path: '/notify/history'
      fullPath: '/notify/history'
      preLoaderRoute: typeof AuthenticatedNotifyHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sinks/http': {
      id: '/_authenticated/sinks/http'
      path: '/sinks/http'
      fullPath: '/sinks/http'
      preLoaderRoute: typeof AuthenticatedSinksHttpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sinks/mqtt': {
      id: '/_authenticated/sinks/mqtt'
      path: '/sinks/mqtt'
      fullPath: '/sinks/mqtt'
      preLoaderRoute: typeof AuthenticatedSinksMqttRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlarmsRoute: typeof AuthenticatedAlarmsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBoardRoute: typeof AuthenticatedBoardRoute
  AuthenticatedCatalogRoute: typeof AuthenticatedCatalogRoute
  AuthenticatedDevicesRoute: typeof AuthenticatedDevicesRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedLicenseRoute: typeof AuthenticatedLicenseRoute
  AuthenticatedLiveRoute: typeof AuthenticatedLiveRoute
  AuthenticatedMqttRoute: typeof AuthenticatedMqttRoute
  AuthenticatedPointsRoute: typeof AuthenticatedPointsRoute
  AuthenticatedPublishRoute: typeof AuthenticatedPublishRoute
  AuthenticatedRuntimeRoute: typeof AuthenticatedRuntimeRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
  AuthenticatedUpgradeRoute: typeof AuthenticatedUpgradeRoute
  AuthenticatedUtilizationRoute: typeof AuthenticatedUtilizationRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAccountPasswordRoute: typeof AuthenticatedAccountPasswordRoute
  AuthenticatedIntegrateOpcuaRoute: typeof AuthenticatedIntegrateOpcuaRoute
  AuthenticatedIntegrateQueryRoute: typeof AuthenticatedIntegrateQueryRoute
  AuthenticatedMonitorDeviceIdRoute: typeof AuthenticatedMonitorDeviceIdRoute
  AuthenticatedNotifyHistoryRoute: typeof AuthenticatedNotifyHistoryRoute
  AuthenticatedSinksHttpRoute: typeof AuthenticatedSinksHttpRoute
  AuthenticatedSinksMqttRoute: typeof AuthenticatedSinksMqttRoute
  AuthenticatedNotifyIndexRoute: typeof AuthenticatedNotifyIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlarmsRoute: AuthenticatedAlarmsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBoardRoute: AuthenticatedBoardRoute,
  AuthenticatedCatalogRoute: AuthenticatedCatalogRoute,
  AuthenticatedDevicesRoute: AuthenticatedDevicesRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedLicenseRoute: AuthenticatedLicenseRoute,
  AuthenticatedLiveRoute: AuthenticatedLiveRoute,
  AuthenticatedMqttRoute: AuthenticatedMqttRoute,
  AuthenticatedPointsRoute: AuthenticatedPointsRoute,
  AuthenticatedPublishRoute: AuthenticatedPublishRoute,
  AuthenticatedRuntimeRoute: AuthenticatedRuntimeRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
  AuthenticatedUpgradeRoute: AuthenticatedUpgradeRoute,
  AuthenticatedUtilizationRoute: AuthenticatedUtilizationRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAccountPasswordRoute: AuthenticatedAccountPasswordRoute,
  AuthenticatedIntegrateOpcuaRoute: AuthenticatedIntegrateOpcuaRoute,
  AuthenticatedIntegrateQueryRoute: AuthenticatedIntegrateQueryRoute,
  AuthenticatedMonitorDeviceIdRoute: AuthenticatedMonitorDeviceIdRoute,
  AuthenticatedNotifyHistoryRoute: AuthenticatedNotifyHistoryRoute,
  AuthenticatedSinksHttpRoute: AuthenticatedSinksHttpRoute,
  AuthenticatedSinksMqttRoute: AuthenticatedSinksMqttRoute,
  AuthenticatedNotifyIndexRoute: AuthenticatedNotifyIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
