/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDevicesRouteImport } from './routes/_authenticated/devices'
import { Route as AuthenticatedMqttRouteImport } from './routes/_authenticated/mqtt'
import { Route as AuthenticatedPointsRouteImport } from './routes/_authenticated/points'
import { Route as AuthenticatedPublishRouteImport } from './routes/_authenticated/publish'
import { Route as AuthenticatedRuntimeRouteImport } from './routes/_authenticated/runtime'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevicesRoute = AuthenticatedDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMqttRoute = AuthenticatedMqttRouteImport.update({
  id: '/mqtt',
  path: '/mqtt',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPointsRoute = AuthenticatedPointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPublishRoute = AuthenticatedPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRuntimeRoute = AuthenticatedRuntimeRouteImport.update({
  id: '/runtime',
  path: '/runtime',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/sign-in': typeof authSignInRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/mqtt': typeof AuthenticatedMqttRoute
  '/points': typeof AuthenticatedPointsRoute
  '/publish': typeof AuthenticatedPublishRoute
  '/runtime': typeof AuthenticatedRuntimeRoute
  '/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/mqtt': typeof AuthenticatedMqttRoute
  '/points': typeof AuthenticatedPointsRoute
  '/publish': typeof AuthenticatedPublishRoute
  '/runtime': typeof AuthenticatedRuntimeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/_authenticated/devices': typeof AuthenticatedDevicesRoute
  '/_authenticated/mqtt': typeof AuthenticatedMqttRoute
  '/_authenticated/points': typeof AuthenticatedPointsRoute
  '/_authenticated/publish': typeof AuthenticatedPublishRoute
  '/_authenticated/runtime': typeof AuthenticatedRuntimeRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/devices'
    | '/mqtt'
    | '/points'
    | '/publish'
    | '/runtime'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/devices'
    | '/mqtt'
    | '/points'
    | '/publish'
    | '/runtime'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/sign-in'
    | '/_authenticated/devices'
    | '/_authenticated/mqtt'
    | '/_authenticated/points'
    | '/_authenticated/publish'
    | '/_authenticated/runtime'
    | '/_authenticated/settings'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devices': {
      id: '/_authenticated/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AuthenticatedDevicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mqtt': {
      id: '/_authenticated/mqtt'
      path: '/mqtt'
      fullPath: '/mqtt'
      preLoaderRoute: typeof AuthenticatedMqttRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/points': {
      id: '/_authenticated/points'
      path: '/points'
      fullPath: '/points'
      preLoaderRoute: typeof AuthenticatedPointsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/publish': {
      id: '/_authenticated/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof AuthenticatedPublishRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/runtime': {
      id: '/_authenticated/runtime'
      path: '/runtime'
      fullPath: '/runtime'
      preLoaderRoute: typeof AuthenticatedRuntimeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDevicesRoute: typeof AuthenticatedDevicesRoute
  AuthenticatedMqttRoute: typeof AuthenticatedMqttRoute
  AuthenticatedPointsRoute: typeof AuthenticatedPointsRoute
  AuthenticatedPublishRoute: typeof AuthenticatedPublishRoute
  AuthenticatedRuntimeRoute: typeof AuthenticatedRuntimeRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDevicesRoute: AuthenticatedDevicesRoute,
  AuthenticatedMqttRoute: AuthenticatedMqttRoute,
  AuthenticatedPointsRoute: AuthenticatedPointsRoute,
  AuthenticatedPublishRoute: AuthenticatedPublishRoute,
  AuthenticatedRuntimeRoute: AuthenticatedRuntimeRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
